### ISSUE TITLE
Maybe rename this repo to `build.transition.monitor`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.transition.monitor#135]
From a conversation with @cjyetman around potential nomenclature for the PACTA ecosystem (PACTA-verse?):

`pacta.*`
These are all standard R packages. No funny business, just functions, unit tests, checks and documentation

`workflow.*`
These are, at the bare minimum, an R script that composes R packages, data, and specific parameters to achieve a certain output (output can be data, figures, reports whatever). These can also contain a Dockerfile to call and implement the script reproducibly.

`build.*`
These would contain more complicated build processes, that depend on several `pacta.*` packages and (potentially) several `workflow.*` repos. The output of this would always be a complete and usable docker image (for now the only one we have is the TM docker image)

**Comment by cjyetman** [comment]
Discussion of whether or not I'm allowed to do this is being tracked here https://github.com/RMI-PACTA/practices/issues/2

A decision still seems murky, and since this repo will hopefully be archived in the next 6 months, I'm throwing in the towel and closing this.
