### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/workflow.transition.monitor#223]
The README refers to `pacta.interactive.report` but I believe that the code responsible for building the report lives now in `pacta.portfolio.report`?

**Comment by cjyetman** [comment]
Yeah, in fact, building the Docker image does not clone or copy in the repos at all anymore, it just installs the packages from their GitHub repos, so it is way out of date.

**Comment by AlexAxthelm** [comment]
Maybe something like

```
> **SUGGESTION:_**  The note content.
```

So we could do 

> **SUGGESTION:** The default R actions ([example](https://github.com/RMI-PACTA/actions/blob/main/examples/R.yml)) in [RMI-PACTA/actions](https://github.com/RMI-PACTA/actions) implements a check for this practice.
