### ISSUE TITLE
Add data-only build process

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.transition.monitor#246]
Now that we are publishing a data-less docker image that is otherwise what we want for CTM, we can improve speed in getting images to testing by preparing a second dockerfile which overwrites the (empty) `pacta-data` and `templates.transition.monitor` directories.

Note, that I am imagining this as a testing-only image, but which can be used to quickly get images up to the BETA platform

**Comment by cjyetman** [comment]
I often test with the existing GHCR images, mounting in the templates and data, as per the README...
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/39963af18715b58e2920b4cf19bf84423407545c/README.md?plain=1#L115-L140

**Comment by AlexAxthelm** [comment]
Yep. I'm basically extending that to include grabbing a dataset from AFS, and a branch from `templates.transition.monitor`, and baking that into a `latest` image that we can put on BETA.
