### ISSUE TITLE
upkeep: review `methodology` parameters in `ProjectParameters_*` config values, maybe deprecate some

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.transition.monitor#253]
Most of the values under the `methodology` header of all of our standard `ProjectParameters_*.yml` files don't seem ever to change (or rarely ever change). In fact, there may even be some that are not used at all in the `web_tool_scripts`.

@cjyetman @AlexAxthelm I am not aware of anybody using this repo "in the wild" with any other config file, so afaik these parameter files represent the complete set of "ways PACTA can be run", do you agree?

If that is the case, and if the values never actually change from their defaults, it might make sense to deprecate them from the API (e.g. by setting them as their default value directly in the relevant `web_tool_script`). Some may even be able to be removed altogether, though this is more dangerous. 

- [ ] `has_revenue` is always `FALSE`
https://github.com/search?q=repo%3ARMI-PACTA%2Fworkflow.transition.monitor+has_revenue&type=code

- [ ] `has_credit` is always `FALSE`
https://github.com/search?q=repo%3ARMI-PACTA%2Fworkflow.transition.monitor+has_credit&type=code

- [ ] `inc_emissionfactors` is always `TRUE`
https://github.com/search?q=repo%3ARMI-PACTA%2Fworkflow.transition.monitor+inc_emissionfactors&type=code

- [ ] `has_map` is almost always`TRUE` (except for one case in `MFM2022` @AlexAxthelm?):
https://github.com/search?q=repo%3ARMI-PACTA%2Fworkflow.transition.monitor%20has_map%3A&type=code

**Comment by jdhoffa** [comment]
Note: I only had a chance to review the values under the `methodology` chunk. There may be others that should have the same treatment.

**Comment by cjyetman** [comment]
see #242 for a fairly complete review (spread through numerous comments) of what's in the params file

When I created [workflow.pacta](https://github.com/RMI-PACTA/workflow.pacta/), I stripped the params down to [only the essentials](https://github.com/RMI-PACTA/workflow.pacta/blob/main/input_dir/default_config.json). If we're moving towards that (and near term deprecating this repo), I'd think this is not something worth putting too much energy into.

**Comment by jdhoffa** [comment]
Awesome and clear! Thanks for the context

**Comment by AlexAxthelm** [comment]
Agree. vote to close this and move relevant documentation effort to workflow.pacta & friends.
