### ISSUE TITLE
Bump versions for GitHub Actions

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.transition.monitor#264]
`actions/checkout`, [`actions/download-artifact`](https://github.com/actions/download-artifact), and [`actions/upload-artifact`](https://github.com/actions/upload-artifact) are all at v4 now.

**Comment by jdhoffa** [comment]
Interesting that [dependabot](https://github.com/RMI-PACTA/workflow.transition.monitor/blob/main/.github/dependabot.yml) didn't notice this? 

Any thoughts on why @cjyetman?

**Comment by cjyetman** [comment]
all usages of `actions/checkout` seem to be up to date
https://github.com/search?q=repo%3ARMI-PACTA%2Fworkflow.transition.monitor%20actions%2Fcheckout&type=code

`actions/download-artifact` and `actions/upload-artifact` were only added in #235 last night
https://github.com/search?q=repo%3ARMI-PACTA%2Fworkflow.transition.monitor%20actions%2Fdownload-artifact&type=code

https://github.com/search?q=repo%3ARMI-PACTA%2Fworkflow.transition.monitor+actions%2Fupload-artifact&type=code

**Comment by cjyetman** [comment]
> Interesting that [dependabot](https://github.com/RMI-PACTA/workflow.transition.monitor/blob/main/.github/dependabot.yml) didn't notice this?
> 
> Any thoughts on why @cjyetman?

Dependabot is scheduled to run on a weekly basis (it doesn't, currently, run on push to PR [not sure if that's currently possible])

https://github.com/RMI-PACTA/workflow.transition.monitor/blob/4e35d836c84341a19baf67650dbf51ef6e2a080e/.github/dependabot.yml#L1-L6

**Comment by jdhoffa** [comment]
Got it! Makes sense

**Comment by AlexAxthelm** [comment]
This was closed prior to a clean build process on branch. Reopening until #269 is closed
