### ISSUE TITLE
`ProjectParameters_GENERAL.yml` cannot work for all timestamps

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.transition.monitor#284]
actually, this is because we need to update the scenarios here
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/b7ed31ade67bceadb9d86858b651b078fed53ed3/parameter_files/ProjectParameters_GENERAL.yml#L57-L61

which then presents the problem that we cannot have a `ProjectParameters_GENERAL.yml` that works for all GENERAL projects for all timestamps 🤔

_Originally posted by @cjyetman in https://github.com/RMI-PACTA/workflow.transition.monitor/issues/283#issuecomment-2009243997_

Because the `ProjectParameters_GENERAL.yml` config (determined by `paste0("ProjectParameters_", project_code, ".yml")`) sets what scenarios should be used, any timestamps using GENERAL must use the same scenarios (and other configured parameters), which is a problem if the scenarios need to be different, e.g. between GENERAL 2022Q4 and GENERAL 2023Q4. This implies that we should maintain separate config files for different combinations of GENERAL and various timestamps, much like we do for the COP initiatives. That also implies that instead of using `GENERAL` for the project/initiative code, we should start using `GENERAL_2022Q4` and `GENERAL_2023Q4` etc., which may have consequences for how Constructiva passes the appropriate project code @AlexAxthelm?

**Comment by cjyetman** [comment]
So, there are more parameters than just the scenarios that need to be changed from GENERAL 2022Q4 to GENERAL 2023Q4... we also need to change the timestamp (obviously? LOL), the start year, and the default scenarios.

**Comment by jdhoffa** [comment]
Noting some conversations that @cjyetman and I had for posterity:
* From a technical perspective, I think having timestamp-specific configs for GENERAL is a good idea (necessary?): e.g. `GENERAL_2021Q4.yml` etc.
* From a user perspective, abstracting away the details as much as possible, so that they only need to select the timestamp is probably favourable
