### ISSUE TITLE
feat: Update CH `2023Q4` config to point to CH peer results

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.transition.monitor#307]
Config is here:
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/b041e3aa04c7829731164b74b7efcec8585d54fb/build/config/rmi_pacta_2023q4_pa2024ch.json#L1-L21

Fake peer results and user results are here:
https://portal.azure.com/#view/Microsoft_Azure_Storage/ContainerMenuBlade/~/overview/storageAccountId/%2fsubscriptions%2ffeef729b-4584-44af-a0f9-4827075512f9%2fresourceGroups%2fRMI-SP-PACTA-DEV%2fproviders%2fMicrosoft.Storage%2fstorageAccounts%2fpactadatadev/path/testing-files/etag/%220x8DC644326E84D85%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride~/false/defaultId//publicAccessVal/None

FYI @AlexAxthelm 

[AB#10958](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10958)

**Comment by AlexAxthelm** [comment]
@jdhoffa @MonikaFu When I'm looking in the user results directory there, I'm not seeing any contents. Have we created anything yet?

**Comment by jdhoffa** [comment]
Ah sorry, nothing has been created yet. 
We're currently working on that here: https://github.com/RMI-PACTA/user_results/pull/24

**Comment by jdhoffa** [comment]
I believe this is done:
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/main/build/config/rmi_pacta_2023q4_pa2024ch.json
