### ISSUE TITLE
archive complete PACTA data input directory during CI/CD

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.transition.monitor#348]
It would be advantageous for whatever constructed version of PACTA data inputs is created in CI/CD for workflow.transition.monitor Docker images was also archived somewhere on Azure for reference/easy access, otherwise one has to reconstruct it manually, which is tedious and error prone.

**Comment by AlexAxthelm** [comment]
I believe that `workflow.data.preparation` already does this (and drops an archive in the same location as the outputs archive), unless I'm missing something

https://github.com/RMI-PACTA/workflow.data.preparation/blob/6001fa51451c0312bf70d3387d1b17dd29236139/run_pacta_data_preparation.R#L905-L917

**Comment by cjyetman** [comment]
but the CI/CD here adds benchmarks and possibly peer files to it before adding to the Docker image... so to inspect the same thing locally one has to reconstruct it manually based on what they think happened during the CI/CD

**Comment by AlexAxthelm** [comment]
Ah. noted. Would you prefer an actual zip to download, or if It's just a tidy collection of links/pointers to the Azure Storage would that be enough?
