### ISSUE TITLE
bug: CI/CD - `docker-build` step failing 

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.transition.monitor#357]
Failing run:
https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/10783374390/job/29905942486

Seems like it can't find the `tar` command:
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/bb969d190fb5dbe4addd0ad0e4d2f919d3fe203c/.github/workflows/build-push-private.yml#L310

Maybe this was removed from a default package list? 

FYI @AlexAxthelm

**Comment by AlexAxthelm** [comment]
Closed in #360
