### ISSUE TITLE
bug: CI/CD - `Run Index Preparation` step failing

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.transition.monitor#358]
Failing run:
https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/10840717571

Seems like it can't find the `jq` command in the called workflow:
https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/blob/c99ff403cc313c8bd2d33161a7f76fd8d29b30fc/.github/workflows/run-index-preparation.yml#L143

FYI @AlexAxthelm 

Relates to #357

[AB#11913](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/11913)

**Comment by AlexAxthelm** [comment]
Noted. Back from PTO, looking into it.

Most recent set of failures. https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/11004556891

**Comment by jdhoffa** [comment]
Welcome back 😊

**Comment by AlexAxthelm** [comment]
Closed via https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/pull/110
