### ISSUE TITLE
Use a `docker-compose` file to set Docker args

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.transition.monitor#82]
Rather than bash scripts

**Comment by cjyetman** [comment]
Even though it's not fully agreed that I should be able to rename this repo as a `build.*` repo, conceptually it is still what I think should be called a `build.*` repo, so my argument above still holds that this repo should not use docker-compose. Closing.

**Comment by AlexAxthelm** [comment]
Agree on closing this. Current README instructions work for local development, and as a team, we've decided to not make this change in PROD.
